apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: linuxserver/homeassistant
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        - name: TZ
          value: DK
        volumeMounts:
        - name: config
          mountPath: /config
        - name: ha-config
          mountPath: /config/configuration.yaml
          subPath: configuration.yaml
      volumes:
      - name: ha-config
        configMap:
          name: home-assistant
      - name: config
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-config
