apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: wireguard
        image: lscr.io/linuxserver/wireguard:latest
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - SYS_MODULE
          privileged: true
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Etc/UTC"
        - name: SERVERURL
          value: {{ .Values.configuration.connectionIp }}
        - name: SERVERPORT
          value: "51820"
        - name: PEERS
          value: "{{ join "," .Values.peers }}"
        - name: ALLOWEDIPS
          value: "0.0.0.0/0"
        - name: LOG_CONFS
          value: "true"
      initContainers:
      - command:
        - sh
        - "-c"
        - ENI=$(ip route get 8.8.8.8 | grep 8.8.8.8 | awk '{print $5}'); sed "s/ENI/$ENI/g"
          /etc/wireguard-secret/wg0.conf.template > /config/wg0.conf; chmod 400 /config/wg0.conf
        - sysctl -w net.ipv4.ip_forward=1
        image: busybox
        name: {{ .Release.Name }}-template-replacement
        volumeMounts:
        - mountPath: "/config"
          name: {{ .Release.Name }}-config
        - mountPath: "/etc/wireguard-secret/"
          name: {{ .Release.Name }}-secret
        volumeMounts:
        - mountPath: /config
          name: config
      volumes:
      - name: config
        emptyDir: {}
      - name: {{ .Values.configuration.secret.name }}
        secret:
          secretName: {{ .Values.configuration.secret.key }}
