apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-config
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.size }}
  storageClassName: {{ .Values.persistentVolumeClaim.storageClass }}
