apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}
  annotations:
    {{- if .Values.config.annotations }}
    {{- toYaml .Values.config.annotations | nindent 4 }}
    {{- end }}
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    {{- if .Values.config.labels }}
    {{- toYaml .Values.config.labels | nindent 4 }}
    {{- end }}
data:
  mosquitto.conf: |

    listener 1883
    user mosquitto

    log_dest stdout

    allow_anonymous {{ .Values.config.allowAnonymous }}

    {{- if .Values.persistence.enabled }}
      persistence true
      persistence_location mosquitto/data/
    {{- end }}

    {{ .Values.config.additionalConfig | nindent 4 }}
