apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.deployment.annotations }}
    {{- toYaml .Values.deployment.annotations | nindent 4}}
    {{- end }}
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    {{- if .Values.deployment.labels }}
    {{- toYaml .Values.deployment.labels | nindent 4}}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mosquitto
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        {{- if .Values.deployment.podAnnotations }}
        {{- toYaml .Values.deployment.podAnnotations | nindent 8}}
        {{- end }}
      labels:
        app.kubernetes.io/name: mosquitto
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        {{- if .Values.deployment.podLabels }}
        {{- toYaml .Values.deployment.podLabels | nindent 8}}
        {{- end }}
    spec:
      {{- if .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.deployment.nodeSelector | nindent 8 }}
      {{- end }}
      securityContext:
        runAsUser: 1883
        runAsGroup: 1883
        fsGroup: 1883
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:{{ .Chart.AppVersion }}
        ports:
        - name: mqtt
          containerPort: 1883
        - name: http
          containerPort: 9001
        volumeMounts:
        - name: data  
          mountPath: /mosquitto/data
        - name: config
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
        resources:
        {{- toYaml .Values.deployment.resources | nindent 10 }}
        {{- if .Values.deployment.startupProbe }}
        {{- toYaml .Values.deployment.startupProbe | nindent 8 }}
        {{- end }}
        {{- if .Values.deployment.readinessProbe }}
        {{- toYaml .Values.deployment.readinessProbe | nindent 8 }}
        {{- end }}
        {{- if .Values.deployment.livenessProbe }}
        {{- toYaml .Values.deployment.livenessProbe | nindent 8 }}
        {{- end }}
      {{- if .Values.serviceMonitor.enabled }}
      - name: mosquitto-exporter
        image: sapcc/mosquitto-exporter
        ports:
        - name: metrics
          containerPort: 8080
        args:
        - --endpoint tcp://localhost:1883
        - --bind-address 0.0.0.0:8080
      {{- end }}
      {{- if hasKey .Values.deployment "tolerations" }}
      tolerations:
      {{- .Values.deployment.tolerations | toYaml | nindent 8 }}
      {{- end }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}
      - name: config
        configMap:
          name: {{ .Release.Name }}