{{- if .Values.service.clusterIp.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.service.clusterIp.annotations }}
    {{- toYaml .Values.service.clusterIp.annotations | nindent 4 }}
    {{- end }}
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    {{- if .Values.service.clusterIp.abels }}
    {{- toYaml .Values.service.clusterIp.labels | nindent 4 }}
    {{- end }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: mqtt
      port: 1883
      targetPort: mqtt
    - name: http
      port: 9001
      targetPort: http
    {{- if .Values.serviceMonitor.enabled }}
    - name: metrics
      port: 8080
      targetPort: metrics
    {{- end }}
---
{{- end }}
{{- if .Values.service.loadBalancer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-lb
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.service.loadBalancer.annotations }}
    {{- toYaml .Values.service.loadBalancer.annotations | nindent 4 }}
    {{- end }}
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    {{- if .Values.service.loadBalancer.labels }}
    {{- toYaml .Values.service.loadBalancer.labels | nindent 4 }}
    {{- end }}
spec:
  selector:
    app: {{ .Release.Name }}
  type: LoadBalancer
  ports:
    - name: mqtt
      port: 1883
      targetPort: mqtt
{{- end }}
