apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
    - name: http
      port: 9001
      targetPort: 9001
---
{{- if .Values.service.loadBalancer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-lb
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
  type: LoadBalancer
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
{{- end }}
