apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        env:
        - name: MODBUS_TO_MQTT_CONFIG_PATH
          value: "/config"
        volumeMounts:
        - name: {{ .Release.Name }}-config
          mountPath: /config.yaml
          subPath: config.yaml
      {{- if hasKey .Values "tolerations" }}
      tolerations:
      {{- .Values.tolerations | toYaml | nindent 8 }}
      {{- end }}
      imagePullSecrets: 
      - name: {{ .Values.image.pullSecret }}
      volumes:
      - name: {{ .Release.Name }}-config
        configMap:
          name: {{ .Release.Name }}
