{{- if .Values.config.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: 60s
      scrapeTimeout: 10s
      scheme: http
{{- end }}
