
plex:
  advertisementAddress: 
  timeZone: UTC
  pu_id: 1000
  pg_id: 1000
  port: 32400
  claimCode: 
  gdm_ports: true
  
deployment:
  labels:
  annotations:
  podLabels: {}
  podAnnotations: {}
  env: []
  hostNetwork: false

  resources:
    requests:
      cpu: 250m
      memory: 250M
    limits:
      cpu: 1000m
      memory: 1000Mi

  nodeSelector: {}
  tolerations: []

  startupProbe:
  readinessProbe:
  livenessProbe:

service:
    enabled: true
    type: LoadBalancer
    labels: []
    annotations: []

ingress:
  enabled: false
  hostname: ""
  ingressClass: ""
  labels: {}
  annotations: {}

persistence:
  enabled: true
  storageClass: ""
  size: 1Gi
  accessModes:
  - ReadWriteOnce
  annotations: {}
  labels: {}

additionalVolumes: []
# - name: name
#   claim: claim