
deployment:
  labels:
  annotations:
  podLabels: {}
  podAnnotations: {}

  resources:
    requests:
      cpu: 250m
      memory: 250M
    limits:
      cpu: 1000m
      memory: 1000Mi

  nodeSelector: {}
  tolerations: []

  startupProbe:
  readinessProbe:
  livenessProbe:

service:
    enabled: true
    type: ClusterIP
    labels: []
    annotations: []

ingress:
  enabled: false
  hostname: ""
  ingressClass: ""
  labels: {}
  annotations: {}

volumes: []
# - name: 
#   claim: 