apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: acockburn/appdaemon:latest
        env:
        - name: HA_URL
          value: {{ .Values.homeAssistant.url }}:{{ .Values.homeAssistant.port }}
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.homeAssistant.token.secret }}
              key: {{ .Values.homeAssistant.token.key }}
        - name: VERT_VERIFY
          value: "{{ .Values.homeAssistant.verifySsl }}"
        volumeMounts:
        - name: config
          mountPath: /conf
      {{ if hasKey .Values.config "fromRepo" }}
      initContainers:
      {{ if eq .Values.config.fromRepo.type "git" }}
      - name: git-clone
        image: alpine/git:latest
        command:
        - sh
        - -c
        - |
          set -e
          git clone https://$USERNAME:$TOKEN@{{ .Values.config.fromRepo.repo }} /repo
          cd /repo
          git checkout {{ .Values.config.fromRepo.branch }}
          cp -r /repo/* /config
        env:
        - name: USERNAME
          value: {{ .Values.config.fromRepo.credentials.username }}
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.config.fromRepo.credentials.token.secret }}
              key: {{ .Values.config.fromRepo.credentials.token.key }}
        volumeMounts:
        - name: config
          mountPath: /config
      {{- end }}
      {{- end }}
      volumes:
      - name: config
        emptyDir: {}
---
