apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Release.Name }}
        image: acockburn/appdaemon:latest
        env:
        {{- if hasKey .Values "homeAssistant" }}
        {{- if .Values.homeAssistant.token.secret }}
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.homeAssistant.token.secret }}
              key: {{ .Values.homeAssistant.token.key }}
        {{- end }}
        {{- end }}
        {{- if hasKey .Values "mqtt" }}
        {{- if .Values.mqtt.password.secret }}
        - name: MQTT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.mqtt.password.secret }}
              key: {{ .Values.mqtt.password.key }}
        {{- end }}
        {{- end }}
        volumeMounts:
        - name: config
          mountPath: /conf
      {{ if hasKey .Values.config "fromRepo" }}
      initContainers:
      {{ if eq .Values.config.fromRepo.type "git" }}
      - name: git-clone
        image: alpine/git:latest
        command:
        - sh
        - -c
        - |
          set -e
          git clone https://$USERNAME:$TOKEN@{{ .Values.config.fromRepo.repo }} /repo
          cd /repo
          git checkout {{ .Values.config.fromRepo.branch }}
          cp -r /repo/* /config
          {{- if not .Values.config.useAppdaemonConfigFromRepo }}
          cp -f /appdaemon.yaml /config/appdaemon.yaml
          {{- end }}
        env:
        - name: USERNAME
          value: {{ .Values.config.fromRepo.credentials.username }}
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.config.fromRepo.credentials.token.secret }}
              key: {{ .Values.config.fromRepo.credentials.token.key }}
        volumeMounts:
        - name: config
          mountPath: /config
        {{- if not .Values.config.useAppdaemonConfigFromRepo }}
        - name: appdaemon
          mountPath: /appdaemon.yaml
          subPath: appdaemon.yaml
        {{- end }}
      {{- end }}
      {{- end }}
      {{- if hasKey .Values "tolerations" }}
      tolerations:
      {{- .Values.tolerations | toYaml | nindent 8 }}
      {{- end }}
      volumes:
      - name: config
        emptyDir: {}
      {{- if not .Values.config.useAppdaemonConfigFromRepo }}
      - name: appdaemon
        configMap:
          name: {{ .Release.Name }}
      {{- end }}
---
