{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.service.annotations }}
    {{- toYaml .Values.service.annotations | nindent 4}}
    {{- end }}
  labels:
    app.kubernetes.io/name: plex
    app.kubernetes.io/component: plex
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    {{- if .Values.service.labels }}
    {{- toYaml .Values.service.labels | nindent 4}}
    {{- end }}
spec:
  selector:
    app.kubernetes.io/name: plex
    app.kubernetes.io/component: plex
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
  ports:
    - name: web
      protocol: TCP
      port: {{ .Values.plex.port }}
      targetPort: web
    {{- if .Values.plex.gdm_ports }}
    - name: gdm-1
      port: 32410
      protocol: UDP
      targetPort: gdm-1
    - name: gdm-2
      port: 32412
      protocol: UDP
      targetPort: gdm-2
    - name: gdm-3
      port: 32413
      protocol: UDP
      targetPort: gdm-3
    - name: gdm-4
      port: 32414
      protocol: UDP
      targetPort: gdm-4
    {{- end }}
{{- end }}