apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.service.annotations }}
    {{- toYaml .Values.service.annotations | nindent 4}}
    {{- end }}
  labels:
    app.kubernetes.io/name: plex
    app.kubernetes.io/component: plex
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    {{- if .Values.service.labels }}
    {{- toYaml .Values.service.labels | nindent 4}}
    {{- end }}
spec:
  selector:
    app.kubernetes.io/name: plex
    app.kubernetes.io/component: plex
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: ClusterIp
  ports:
    - name: web
      protocol: TCP
      port: 32400
      targetPort: web
