image:
  registry: ghcr.io
  name: matlerbru/go-modbus-to-mqtt
  tag: latest

config:

  mqtt:
    address: ""
    port: 1883
    qos: 2

    mainTopic: modbus-to-mqtt

  modbus:
    address: ""
    port: 502

    blocks: []

    scanInterval: 80

  metrics:
    enabled: false

tolerations: []

nodeSelector: {}