apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-transmission
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-transmission
  {{ if hasKey .Values "service" }}
  {{ if hasKey .Values.service "transmission" }}
  {{ if .Values.service.transmission.type }}
  type: {{ .Values.service.transmission.type }}
  {{- end }}{{ end }}{{ end }}
  ports:
    - name: web
      port: 9091
      targetPort: 9091
      {{ if hasKey .Values "service" }}
      {{ if hasKey .Values.service "transmission" }}
      {{- if .Values.service.transmission.nodePort }}
      nodePort: {{ .Values.service.transmission.nodePort }}
      {{- end }}{{ end }}{{ end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-jellyfin
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-jellyfin
  {{ if hasKey .Values "service" }}
  {{ if hasKey .Values.service "jellyfin" }}
  {{ if .Values.service.jellyfin.type }}
  type: {{ .Values.service.jellyfin.type }}
  {{- end }}{{ end }}{{ end }}
  ports:
    - port: 8096
      targetPort: 8096
      {{ if hasKey .Values "service" }}
      {{ if hasKey .Values.service "jellyfin" }}
      {{- if .Values.service.jellyfin.nodePort }}
      nodePort: {{ .Values.service.jellyfin.nodePort }}
      {{- end }}{{ end }}{{ end }}