tolerations: []

ingress:
    enabled: false
    annotations: []
    host: ""

homeAssistant:
    url: ""
    port: 8123
    token:
        secret: ""
        key: ""
    verifySsl: true
    settings:
        {}
        # latitude: 52.43
        # longitude: 13.22
        # elevation: 100
        # time_zone: "Europe/Berlin"
        # unit_system: metric

mqtt:
    host: ""
    port: 1883
    username: ""
    password:
        secret: ""
        key: ""

config: {}
#    fromRepo:
#        type: git
#        repo: ""
#        branch: main
#        credentials:
#            username: ""
#            token:
#                secret: github-access-token
#                key: TOKEN
---

