tolerations: []

persistence:
    enabled: false
    storageClass: ""
    size: 1Gi

homeAssistant:
    url: ""
    port: 8123
    token:
        secret: ""
        key: ""

config: {}
#    fromRepo:
#        type: git
#        repo: ""
#        branch: main
#        credentials:
#            username: ""
#            token:
#                secret: github-access-token
#                key: TOKEN
---

