apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-script
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.configMap.annotations }}
    {{- toYaml .Values.configMap.annotations | nindent 4}}
    {{- end }}
  labels:
    app.kubernetes.io/name: unifi-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Values.configMap.labels }}
    {{- toYaml .Values.configMap.labels | nindent 4}}
    {{- end }}
data:
  init-mongo.sh: |
    #!/bin/bash
    set -e
    "$mongo" <<EOF
    try {
      db.getSiblingDB("admin").auth("${MONGO_INITDB_ROOT_USERNAME}", "${MONGO_INITDB_ROOT_PASSWORD}");
    } catch (e) {
      // ignore auth errors during no-auth phase
    }

    var authDb = db.getSiblingDB("${MONGO_AUTHSOURCE:-admin}");

    if (!authDb.getUser("${MONGO_USER}")) {
      authDb.createUser({
        user: "${MONGO_USER}",
        pwd: "${MONGO_PASS}",
        roles: [
          { role: "dbOwner", db: "${MONGO_DBNAME}" },
          { role: "dbOwner", db: "${MONGO_DBNAME}_stat" },
          { role: "dbOwner", db: "${MONGO_DBNAME}_audit" }
        ]
      });
    }
    EOF
