apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.persistence.config.annotations }}
    {{- toYaml .Values.persistence.config.annotations | nindent 4}}
    {{- end }}
  labels:
    app.kubernetes.io/name: unifi-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.iombrunhoej: {{ .Chart.AppVersion | quote }}
    {{- if .Values.persistence.config.labels }}
    {{- toYaml .Values.persistence.config.labels | nindent 4}}
    {{- end }}
spec:
  accessModes:
  {{- range $mode := .Values.persistence.config.accessModes }}
    - {{ $mode }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }} 
  storageClassName: {{ .Values.persistence.config.storageClass }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-data
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.persistence.data.annotations }}
    {{- toYaml .Values.persistence.data.annotations | nindent 4}}
    {{- end }}
  labels:
    app.kubernetes.io/name: unifi-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.iombrunhoej: {{ .Chart.AppVersion | quote }}
    {{- if .Values.persistence.data.labels }}
    {{- toYaml .Values.persistence.data.labels | nindent 4}}
    {{- end }}
spec:
  accessModes:
  {{- range $mode := .Values.persistence.data.accessModes }}
    - {{ $mode }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }} 
  storageClassName: {{ .Values.persistence.data.storageClass }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mongo
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.persistence.mongo.annotations }}
    {{- toYaml .Values.persistence.mongo.annotations | nindent 4}}
    {{- end }}
  labels:
    app.kubernetes.io/name: unifi-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.iombrunhoej: {{ .Chart.AppVersion | quote }}
    {{- if .Values.persistence.mongo.labels }}
    {{- toYaml .Values.persistence.mongo.labels | nindent 4}}
    {{- end }}
spec:
  accessModes:
  {{- range $mode := .Values.persistence.mongo.accessModes }}
    - {{ $mode }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.mongo.size }} 
  storageClassName: {{ .Values.persistence.mongo.storageClass }}