
{{ if ( not .Values.secret.existingkey.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongo
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.persistence.config.annotations }}
    {{- toYaml .Values.persistence.config.annotations | nindent 4}}
    {{- end }}
  labels:
    app.kubernetes.io/name: unifi-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    {{- if .Values.persistence.config.labels }}
    {{- toYaml .Values.persistence.config.labels | nindent 4}}
    {{- end }}
stringData:
  mongo-initdb-root-password: {{ randAlphaNum 40 | nospace}}
  mongo-pass: {{ randAlphaNum 40 | nospace}}
{{- end }}
