
{{ if ( not .Values.secret.existingkey.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongo-db
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install
stringData:
  mongo-initdb-root-password: {{ randAlphaNum 40 | nospace}}
  mongo-pass: {{ randAlphaNum 40 | nospace}}
{{- end }}
