apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.unifiController.service.annotations }}
    {{- toYaml .Values.unifiController.service.annotations | nindent 4}}
    {{- end }}
  labels:
    app.kubernetes.io/name: unifi-controller
    app.kubernetes.io/component: unifi-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    {{- if .Values.unifiController.service.labels }}
    {{- toYaml .Values.unifiController.service.labels | nindent 4}}
    {{- end }}
spec:
  selector:
    app.kubernetes.io/name: unifi-controller
    app.kubernetes.io/component: unifi-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: LoadBalancer
  ports:
    - name: https
      protocol: TCP
      port: 8443
      targetPort: https
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
    - name: stun
      protocol: UDP
      port: 3478
      targetPort: stun
    - name: ap-discovery
      protocol: UDP
      port: 10001
      targetPort: ap-discovery
    - name: l2-discovery
      protocol: UDP
      port: 1900
      targetPort: l2-discovery
    - name: mobile-test
      port: 6789
      targetPort: mobile-test
    - name: remote-syslog
      protocol: UDP
      port: 5514
      targetPort: remote-syslog
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongo
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.mongo.service.annotations }}
    {{- toYaml .Values.mongo.service.annotations | nindent 4}}
    {{- end }}
  labels:
    app.kubernetes.io/name: unifi-controller
    app.kubernetes.io/component: mongo
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    {{- if .Values.mongo.service.labels }}
    {{- toYaml .Values.mongo.service.labels | nindent 4}}
    {{- end }}
spec:
  selector:
    app.kubernetes.io/name: unifi-controller
    app.kubernetes.io/component: mongo
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 27017
      targetPort: http