{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.ingress.annotations }}
    {{- toYaml .Values.ingress.annotations | nindent 4}}
    {{- end }}
  labels:
    app.kubernetes.io/name: transmission
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    {{- if .Values.ingress.labels }}
    {{- toYaml .Values.ingress.labels | nindent 4}}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClass }}
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              name: rpc
{{- end }}