
unifiController:

  deployment:

    labels: {}
    annotation: {}

    podLabels: {}
    podAnnotations: {}

    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 250m
        memory: 256Mi

    nodeSelector: {}
    tolerations: []

    startupProbe:
      exec:
        command:
          - /bin/sh
          - -c
          - |
            loc=$(curl -sS -k -D - https://127.0.0.1:8443/ \
              | grep -i Location \
              | awk '{print $2}' \
              | tr -d '\r')

            if [ "$loc" = "/setup/" ] || [ "$loc" = "/manage" ]; then
              exit 0
            else
              exit 1
            fi
      periodSeconds: 10
      failureThreshold: 60
      timeoutSeconds: 5

    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 3
      successThreshold: 1
      failureThreshold: 3

    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 20
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 5

    initContainer:
      image:
        tag: latest

  service:
    labels: {}
    annotations: {}

mongo:

  deployment:

    image:
      tag: 4.4

    labels: {}
    annotation: {}

    podLabels: {}
    podAnnotations: {}

    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 250m
        memory: 256Mi

    nodeSelector: {}
    tolerations: []

    startupProbe:
      exec:
        command:
          - mongo
          - --eval
          - "db.runCommand({ ping: 1 })"
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 5
      failureThreshold: 30

    readinessProbe:
      tcpSocket:
      exec:
        command:
          - mongo
          - --eval
          - "db.runCommand({ ping: 1 })"
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3

    livenessProbe:
      tcpSocket:
      exec:
        command:
          - mongo
          - --eval
          - "db.runCommand({ ping: 1 })"
      initialDelaySeconds: 30
      periodSeconds: 20
      timeoutSeconds: 5
      failureThreshold: 5

  service:
    labels: {}
    annotations: {}

configMap:
  labels: {}
  annotations: {}

persistence:
  config:
    storageClass: ""
    size: 1Gi
    accessModes:
    - ReadWriteOnce
    annotations: {}
    labels: {}
  data:
    storageClass: ""
    size: 1Gi
    accessModes:
    - ReadWriteOnce
    annotations: {}
    labels: {}
  mongo:
    storageClass: ""
    size: 1Gi
    accessModes:
    - ReadWriteOnce
    annotations: {}
    labels: {}

secret:
  existingkey:
    enabled: false
    name: ""
  labels: {}
  annotations: {}
