apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.deployment.annotations }}
    {{- toYaml .Values.deployment.annotations | nindent 4}}
    {{- end }}
  labels:
    app.kubernetes.io/name: adguard
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    {{- if .Values.deployment.labels }}
    {{- toYaml .Values.deployment.labels | nindent 4}}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: adguard
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        {{- if .Values.deployment.podAnnotations }}
        {{- toYaml .Values.deployment.podAnnotations | nindent 8}}
        {{- end }}
      labels:
        app.kubernetes.io/name: adguard
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        {{- if .Values.deployment.podLabels }}
        {{- toYaml .Values.deployment.podLabels | nindent 8}}
        {{- end }}
    spec:
      {{- if .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.deployment.nodeSelector | nindent 8 }}
      {{- end }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 100
        runAsNonRoot: true
      containers:
      - name: adguard
        image: adguard/adguardhome:{{ .Chart.AppVersion }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
              - NET_BIND_SERVICE
        ports:
        - name: http
          containerPort: 80
        - name: http-initial 
          containerPort: 3000
        - name: dns
          containerPort: 53 
        volumeMounts:
        {{- if .Values.persistence.work.enabled }}
        - name: work
          mountPath: /opt/adguardhome/work
        {{- end }}
        {{- if .Values.persistence.config.enabled }}
        - name: config
          mountPath: /opt/adguardhome/conf
        {{- end }}
        resources:
        {{- toYaml .Values.deployment.resources | nindent 10 }}
        startupProbe:
        {{- toYaml .Values.deployment.startupProbe | nindent 10 }}
        readinessProbe:
        {{- toYaml .Values.deployment.readinessProbe | nindent 10 }}
        livenessProbe:
        {{- toYaml .Values.deployment.livenessProbe | nindent 10 }}
      {{- if hasKey .Values.deployment "tolerations" }}
      tolerations:
      {{- .Values.deployment.tolerations | toYaml | nindent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.persistence.work.enabled }}
      - name: work
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-work
      {{- end }}
      {{- if .Values.persistence.config.enabled }}
      - name: config
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-config
      {{- end }}
