apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-work
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.work.size }}
  {{- if .Values.persistentVolumeClaim.work.storageClass }}
  storageClassName: {{ .Values.persistentVolumeClaim.work.storageClass }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.config.size }}
  {{- if .Values.persistentVolumeClaim.config.storageClass }}
  storageClassName: {{ .Values.persistentVolumeClaim.config.storageClass }}
  {{- end }}
