persistentVolumeClaim:
  transmission:
    storageClass: synology-backup
    size: 100Mi
  jellyfinConfig:
    storageClass: synology-backup
    size: 1Gi
  jellyfinCache:
    storageClass: synology-backup
    size: 1Gi
  data:
    storageClass: synology
    size: 2000Gi

service:
  transmission:
    type: LoadBalancer

networkPolicy:
  allowedRanges: []
  disallowedRanges: []

ingress:
  transmission:
    host: ""
  jellyfin:
    host: ""

openvpn:
  # Find at:
  # https://haugene.github.io/docker-transmission-openvpn/supported-providers/
  provider: ""
  config: ""
