service:
  transmission:
    type: LoadBalancer

ingress:
  transmission:
    annotations: {}
    host: ""
  jellyfin:
    annotations: {}
    host: ""

openvpn:
  # Find at:
  # https://haugene.github.io/docker-transmission-openvpn/supported-providers/
  provider: ""
  config: ""

persistence:
  enabled: true
  transmission:
    storageClass: ""
    size: 100Mi
  jellyfinConfig:
    storageClass: ""
    size: 1Gi
  jellyfinCache:
    enabled: false
    storageClass: ""
    size: 1Gi
  data:
    storageClass: ""
    size: 2000Gi
